options:
  hostname:
    type: string
    description: "Hostname for the server"
  repository:
    type: string
    default: diaspora/diaspora
    description: "Repository to use. Does not normally need to be changed."
  branch:
    type: string
    default: master
    description: "Branch to use. Does not normally need to be changed."
  podname:
    type: string
    default: diaspora*
    description: "A name for the pod. The most difficult setting. Can be changed later."
  ssl_key:
    type: string
    description: SSL private key for pod domain. See readme how to best use this configuration value. Must be unencrypted.
  ssl_cert:
    type: string
    description: SSL cert for pod domain. See readme how to best use this configuration value.
  ssl_snakebite:
    type: boolean
    description: "If ssl_cert and ssl_key not set, shall we use the snakebite cert?"
    default: true
  statistics:
    type: boolean
    description: "Enable statistics from the pod? This includes user and post counts. Statistics will be exposed at /statistics.json"
    default: false
